services:
  invoice-fe:
    image: trananh2024/invoice-fe-web:production
    container_name: invoice-fe
    restart: always
    ports:
      - '8081:80'
    networks:
      - api-app-net
networks:
  api-app-net:
    driver: bridge
