import { ITableConfig } from '../model/common';

export const TABLE_COLUMNS: ITableConfig[] = [
  {
    id: 'name',
    label: 'Name',
    field: 'name',
    type: 'text',
    minWidth: '200px',
    frozen: true,
    frozenAlign: 'left',
    cssClass: 'font-bold',
    headerClass: 'font-bold',
    sortable: true,
    filterable: true,
  },
  {
    id: 'id',
    label: 'Id',
    field: 'id',
    type: 'text',
    minWidth: '100px',
    sortable: true,
    filterable: true,
  },
  {
    id: 'country',
    label: 'Country',
    field: 'country',
    type: 'text',
    minWidth: '200px',
    sortable: true,
    filterable: true,
  },
  {
    id: 'date',
    label: 'Date',
    field: 'date',
    type: 'date',
    minWidth: '200px',
    sortable: true,
    filterable: true,
    pipe: 'date',
    pipeFormat: 'dd/MM/yyyy',
  },
  {
    id: 'company',
    label: 'Company',
    field: 'company',
    type: 'text',
    minWidth: '200px',
    sortable: true,
    filterable: true,
  },
  {
    id: 'status',
    label: 'Status',
    field: 'status',
    type: 'badge',
    minWidth: '200px',
    sortable: true,
    filterable: true,
    badgeMap: {
      active: 'Active',
      inactive: 'Inactive',
      pending: 'Pending',
    },
    badgeColor: 'info',
  },
  {
    id: 'activity',
    label: 'Activity',
    field: 'activity',
    type: 'text',
    minWidth: '200px',
    sortable: true,
    filterable: true,
  },
  {
    id: 'representative',
    label: 'Representative',
    field: 'representative',
    type: 'text',
    minWidth: '200px',
    sortable: true,
    filterable: true,
  },
  {
    id: 'balance',
    label: 'Balance',
    field: 'balance',
    type: 'currency',
    minWidth: '200px',
    frozen: true,
    frozenAlign: 'right',
    cssClass: 'font-bold',
    headerClass: 'font-bold',
    sortable: true,
    filterable: true,
    pipe: 'currency',
    pipeLocale: 'en-US',
  },
];
