export const data = [
  {
    id: 1000,
    name: 'James Butua aifgai udaiudh aiduhasid aiudas ai aidgasi dt',
    country: {
      name: 'Algeria',
      code: 'dz',
    },
    company: 'Benton, John B Jr',
    status: 'unqualified',
    verified: true,
    activity: 17,
    representative: {
      name: 'Ioni Bowcher',
      image: 'ionibowcher.png',
    },
    balance: 70663,
  },
  {
    id: 1001,
    name: 'Josephine Darakjy',
    country: {
      name: 'Egypt',
      code: 'eg',
    },
    company: 'Chanay, Jeffrey A Esq',
    status: 'negotiation',
    verified: true,
    activity: 0,
    representative: {
      name: 'Amy Elsner',
      image: 'amyelsner.png',
    },
    balance: 82429,
  },
  {
    id: 1002,
    name: 'Art Venere',
    country: {
      name: 'Panama',
      code: 'pa',
    },
    company: 'Chemel, James L Cpa',
    status: 'qualified',
    verified: false,
    activity: 63,
    representative: {
      name: 'Asiya Javayant',
      image: 'asiyajavayant.png',
    },
    balance: 28334,
  },
  {
    id: 1003,
    name: 'Lenna Paprocki',
    country: {
      name: 'Slovenia',
      code: 'si',
    },
    company: 'Feltz Printing Service',
    status: 'new',
    verified: false,
    activity: 37,
    representative: {
      name: 'Xuxue Feng',
      image: 'xuxuefeng.png',
    },
    balance: 88521,
  },
  {
    id: 1004,
    name: 'Donette Foller',
    country: {
      name: 'South Africa',
      code: 'za',
    },
    company: 'Printing Dimensions',
    status: 'negotiation',
    verified: true,
    activity: 33,
    representative: {
      name: 'Asiya Javayant',
      image: 'asiyajavayant.png',
    },
    balance: 93905,
  },
  {
    id: 1005,
    name: 'Simona Morasca',
    country: {
      name: 'Egypt',
      code: 'eg',
    },
    company: 'Chapman, Ross E Esq',
    status: 'qualified',
    verified: false,
    activity: 68,
    representative: {
      name: 'Ivan Magalhaes',
      image: 'ivanmagalhaes.png',
    },
    balance: 50041,
  },
  {
    id: 1006,
    name: 'Mitsue Tollner',
    country: {
      name: 'Paraguay',
      code: 'py',
    },
    company: 'Morlong Associates',
    status: 'renewal',
    verified: true,
    activity: 54,
    representative: {
      name: 'Ivan Magalhaes',
      image: 'ivanmagalhaes.png',
    },
    balance: 58706,
  },
  {
    id: 1007,
    name: 'Leota Dilliard',
    country: {
      name: 'Serbia',
      code: 'rs',
    },
    company: 'Commercial Press',
    status: 'renewal',
    verified: true,
    activity: 69,
    representative: {
      name: 'Onyama Limba',
      image: 'onyamalimba.png',
    },
    balance: 26640,
  },
  {
    id: 1008,
    name: 'Sage Wieser',
    country: {
      name: 'Egypt',
      code: 'eg',
    },
    company: 'Truhlar And Truhlar Attys',
    status: 'unqualified',
    verified: true,
    activity: 76,
    representative: {
      name: 'Ivan Magalhaes',
      image: 'ivanmagalhaes.png',
    },
    balance: 65369,
  },
  {
    id: 1009,
    name: 'Kris Marrier',
    country: {
      name: 'Mexico',
      code: 'mx',
    },
    company: 'King, Christopher A Esq',
    status: 'negotiation',
    verified: false,
    activity: 3,
    representative: {
      name: 'Onyama Limba',
      image: 'onyamalimba.png',
    },
    balance: 63451,
  },
  {
    id: 1010,
    name: 'Minna Amigon',
    country: {
      name: 'Romania',
      code: 'ro',
    },
    company: 'Dorl, James J Esq',
    status: 'qualified',
    verified: false,
    activity: 38,
    representative: {
      name: 'Anna Fali',
      image: 'annafali.png',
    },
    balance: 71169,
  },
  {
    id: 1011,
    name: 'Abel Maclead',
    country: {
      name: 'Singapore',
      code: 'sg',
    },
    company: 'Rangoni Of Florence',
    status: 'qualified',
    verified: true,
    activity: 87,
    representative: {
      name: 'Bernardo Dominic',
      image: 'bernardodominic.png',
    },
    balance: 96842,
  },
  {
    id: 1012,
    name: 'Kiley Caldarera',
    country: {
      name: 'Serbia',
      code: 'rs',
    },
    company: 'Feiner Bros',
    status: 'unqualified',
    verified: false,
    activity: 80,
    representative: {
      name: 'Onyama Limba',
      image: 'onyamalimba.png',
    },
    balance: 92734,
  },
  {
    id: 1013,
    name: 'Graciela Ruta',
    country: {
      name: 'Chile',
      code: 'cl',
    },
    company: 'Buckley Miller & Wright',
    status: 'negotiation',
    verified: false,
    activity: 59,
    representative: {
      name: 'Amy Elsner',
      image: 'amyelsner.png',
    },
    balance: 45250,
  },
  {
    id: 1014,
    name: 'Cammy Albares',
    country: {
      name: 'Philippines',
      code: 'ph',
    },
    company: 'Rousseaux, Michael Esq',
    status: 'new',
    verified: true,
    activity: 90,
    representative: {
      name: 'Asiya Javayant',
      image: 'asiyajavayant.png',
    },
    balance: 30236,
  },
  {
    id: 1015,
    name: 'Mattie Poquette',
    country: {
      name: 'Venezuela',
      code: 've',
    },
    company: 'Century Communications',
    status: 'negotiation',
    verified: false,
    activity: 52,
    representative: {
      name: 'Anna Fali',
      image: 'annafali.png',
    },
    balance: 64533,
  },
  {
    id: 1016,
    name: 'Meaghan Garufi',
    country: {
      name: 'Malaysia',
      code: 'my',
    },
    company: 'Bolton, Wilbur Esq',
    status: 'unqualified',
    verified: false,
    activity: 31,
    representative: {
      name: 'Ivan Magalhaes',
      image: 'ivanmagalhaes.png',
    },
    balance: 37279,
  },
  {
    id: 1017,
    name: 'Gladys Rim',
    country: {
      name: 'Netherlands',
      code: 'nl',
    },
    company: 'T M Byxbee Company Pc',
    status: 'renewal',
    verified: true,
    activity: 48,
    representative: {
      name: 'Stephen Shaw',
      image: 'stephenshaw.png',
    },
    balance: 27381,
  },
  {
    id: 1018,
    name: 'Yuki Whobrey',
    country: {
      name: 'Israel',
      code: 'il',
    },
    company: 'Farmers Insurance Group',
    status: 'negotiation',
    verified: true,
    activity: 16,
    representative: {
      name: 'Bernardo Dominic',
      image: 'bernardodominic.png',
    },
    balance: 9257,
  },
  {
    id: 1019,
    name: 'Fletcher Flosi',
    country: {
      name: 'Argentina',
      code: 'ar',
    },
    company: 'Post Box Services Plus',
    status: 'renewal',
    verified: true,
    activity: 19,
    representative: {
      name: 'Xuxue Feng',
      image: 'xuxuefeng.png',
    },
    balance: 67783,
  },
  {
    id: 1020,
    name: 'Bette Nicka',
    country: {
      name: 'Paraguay',
      code: 'py',
    },
    company: 'Sport En Art',
    status: 'renewal',
    verified: false,
    activity: 100,
    representative: {
      name: 'Onyama Limba',
      image: 'onyamalimba.png',
    },
    balance: 4609,
  },
  {
    id: 1021,
    name: 'Veronika Inouye',
    country: {
      name: 'Ecuador',
      code: 'ec',
    },
    company: 'C 4 Network Inc',
    status: 'renewal',
    verified: false,
    activity: 72,
    representative: {
      name: 'Ioni Bowcher',
      image: 'ionibowcher.png',
    },
    balance: 26565,
  },
  {
    id: 1022,
    name: 'Willard Kolmetz',
    country: {
      name: 'Tunisia',
      code: 'tn',
    },
    company: 'Ingalls, Donald R Esq',
    status: 'renewal',
    verified: true,
    activity: 94,
    representative: {
      name: 'Asiya Javayant',
      image: 'asiyajavayant.png',
    },
    balance: 75876,
  },
  {
    id: 1023,
    name: 'Maryann Royster',
    country: {
      name: 'Belarus',
      code: 'by',
    },
    company: 'Franklin, Peter L Esq',
    status: 'qualified',
    verified: false,
    activity: 56,
    representative: {
      name: 'Elwin Sharvill',
      image: 'elwinsharvill.png',
    },
    balance: 41121,
  },
  {
    id: 1024,
    name: 'Alisha Slusarski',
    country: {
      name: 'Iceland',
      code: 'is',
    },
    company: 'Wtlz Power 107 Fm',
    status: 'qualified',
    verified: true,
    activity: 7,
    representative: {
      name: 'Stephen Shaw',
      image: 'stephenshaw.png',
    },
    balance: 91691,
  },
  {
    id: 1025,
    name: 'Allene Iturbide',
    country: {
      name: 'Italy',
      code: 'it',
    },
    company: 'Ledecky, David Esq',
    status: 'qualified',
    verified: true,
    activity: 1,
    representative: {
      name: 'Ivan Magalhaes',
      image: 'ivanmagalhaes.png',
    },
    balance: 40137,
  },
  {
    id: 1026,
    name: 'Chanel Caudy',
    country: {
      name: 'Argentina',
      code: 'ar',
    },
    company: 'Professional Image Inc',
    status: 'new',
    verified: true,
    activity: 26,
    representative: {
      name: 'Ioni Bowcher',
      image: 'ionibowcher.png',
    },
    balance: 21304,
  },
  {
    id: 1027,
    name: 'Ezekiel Chui',
    country: {
      name: 'Ireland',
      code: 'ie',
    },
    company: 'Sider, Donald C Esq',
    status: 'new',
    verified: false,
    activity: 76,
    representative: {
      name: 'Amy Elsner',
      image: 'amyelsner.png',
    },
    balance: 60454,
  },
  {
    id: 1028,
    name: 'Willow Kusko',
    country: {
      name: 'Romania',
      code: 'ro',
    },
    company: 'U Pull It',
    status: 'qualified',
    verified: true,
    activity: 7,
    representative: {
      name: 'Onyama Limba',
      image: 'onyamalimba.png',
    },
    balance: 17565,
  },
  {
    id: 1029,
    name: 'Bernardo Figeroa',
    country: {
      name: 'Israel',
      code: 'il',
    },
    company: 'Clark, Richard Cpa',
    status: 'renewal',
    verified: true,
    activity: 81,
    representative: {
      name: 'Ioni Bowcher',
      image: 'ionibowcher.png',
    },
    balance: 17774,
  },
  {
    id: 1030,
    name: 'Ammie Corrio',
    country: {
      name: 'Hungary',
      code: 'hu',
    },
    company: 'Moskowitz, Barry S',
    status: 'negotiation',
    verified: true,
    activity: 56,
    representative: {
      name: 'Asiya Javayant',
      image: 'asiyajavayant.png',
    },
    balance: 49201,
  },
  {
    id: 1031,
    name: 'Francine Vocelka',
    country: {
      name: 'Honduras',
      code: 'hn',
    },
    company: 'Cascade Realty Advisors Inc',
    status: 'qualified',
    verified: true,
    activity: 94,
    representative: {
      name: 'Ioni Bowcher',
      image: 'ionibowcher.png',
    },
    balance: 67126,
  },
  {
    id: 1032,
    name: 'Ernie Stenseth',
    country: {
      name: 'Australia',
      code: 'au',
    },
    company: 'Knwz Newsradio',
    status: 'renewal',
    verified: true,
    activity: 68,
    representative: {
      name: 'Xuxue Feng',
      image: 'xuxuefeng.png',
    },
    balance: 76017,
  },
  {
    id: 1033,
    name: 'Albina Glick',
    country: {
      name: 'Ukraine',
      code: 'ua',
    },
    company: 'Giampetro, Anthony D',
    status: 'negotiation',
    verified: true,
    activity: 85,
    representative: {
      name: 'Bernardo Dominic',
      image: 'bernardodominic.png',
    },
    balance: 91201,
  },
  {
    id: 1034,
    name: 'Alishia Sergi',
    country: {
      name: 'Qatar',
      code: 'qa',
    },
    company: 'Milford Enterprises Inc',
    status: 'negotiation',
    verified: false,
    activity: 46,
    representative: {
      name: 'Ivan Magalhaes',
      image: 'ivanmagalhaes.png',
    },
    balance: 12237,
  },
  {
    id: 1035,
    name: 'Solange Shinko',
    country: {
      name: 'Cameroon',
      code: 'cm',
    },
    company: 'Mosocco, Ronald A',
    status: 'qualified',
    verified: true,
    activity: 32,
    representative: {
      name: 'Onyama Limba',
      image: 'onyamalimba.png',
    },
    balance: 34072,
  },
  {
    id: 1036,
    name: 'Jose Stockham',
    country: {
      name: 'Italy',
      code: 'it',
    },
    company: 'Tri State Refueler Co',
    status: 'qualified',
    verified: true,
    activity: 77,
    representative: {
      name: 'Amy Elsner',
      image: 'amyelsner.png',
    },
    balance: 94909,
  },
  {
    id: 1037,
    name: 'Rozella Ostrosky',
    country: {
      name: 'Venezuela',
      code: 've',
    },
    company: 'Parkway Company',
    status: 'unqualified',
    verified: true,
    activity: 66,
    representative: {
      name: 'Amy Elsner',
      image: 'amyelsner.png',
    },
    balance: 57245,
  },
  {
    id: 1038,
    name: 'Valentine Gillian',
    country: {
      name: 'Paraguay',
      code: 'py',
    },
    company: 'Fbs Business Finance',
    status: 'qualified',
    verified: true,
    activity: 25,
    representative: {
      name: 'Bernardo Dominic',
      image: 'bernardodominic.png',
    },
    balance: 75502,
  },
  {
    id: 1039,
    name: 'Kati Rulapaugh',
    country: {
      name: 'Puerto Rico',
      code: 'pr',
    },
    company: 'Eder Assocs Consltng Engrs Pc',
    status: 'renewal',
    verified: false,
    activity: 51,
    representative: {
      name: 'Ioni Bowcher',
      image: 'ionibowcher.png',
    },
    balance: 82075,
  },
  {
    id: 1040,
    name: 'Youlanda Schemmer',
    country: {
      name: 'Bolivia',
      code: 'bo',
    },
    company: 'Tri M Tool Inc',
    status: 'negotiation',
    verified: true,
    activity: 49,
    representative: {
      name: 'Xuxue Feng',
      image: 'xuxuefeng.png',
    },
    balance: 19208,
  },
  {
    id: 1041,
    name: 'Dyan Oldroyd',
    country: {
      name: 'Argentina',
      code: 'ar',
    },
    company: 'International Eyelets Inc',
    status: 'qualified',
    verified: false,
    activity: 5,
    representative: {
      name: 'Amy Elsner',
      image: 'amyelsner.png',
    },
    balance: 50194,
  },
  {
    id: 1042,
    name: 'Roxane Campain',
    country: {
      name: 'France',
      code: 'fr',
    },
    company: 'Rapid Trading Intl',
    status: 'unqualified',
    verified: false,
    activity: 100,
    representative: {
      name: 'Anna Fali',
      image: 'annafali.png',
    },
    balance: 77714,
  },
  {
    id: 1043,
    name: 'Lavera Perin',
    country: {
      name: 'Vietnam',
      code: 'vn',
    },
    company: 'Abc Enterprises Inc',
    status: 'qualified',
    verified: false,
    activity: 71,
    representative: {
      name: 'Stephen Shaw',
      image: 'stephenshaw.png',
    },
    balance: 35740,
  },
  {
    id: 1044,
    name: 'Erick Ferencz',
    country: {
      name: 'Belgium',
      code: 'be',
    },
    company: 'Cindy Turner Associates',
    status: 'unqualified',
    verified: true,
    activity: 54,
    representative: {
      name: 'Amy Elsner',
      image: 'amyelsner.png',
    },
    balance: 30790,
  },
  {
    id: 1045,
    name: 'Fatima Saylors',
    country: {
      name: 'Canada',
      code: 'ca',
    },
    company: 'Stanton, James D Esq',
    status: 'renewal',
    verified: true,
    activity: 93,
    representative: {
      name: 'Onyama Limba',
      image: 'onyamalimba.png',
    },
    balance: 52343,
  },
  {
    id: 1046,
    name: 'Jina Briddick',
    country: {
      name: 'Mexico',
      code: 'mx',
    },
    company: 'Grace Pastries Inc',
    status: 'unqualified',
    verified: false,
    activity: 97,
    representative: {
      name: 'Xuxue Feng',
      image: 'xuxuefeng.png',
    },
    balance: 53966,
  },
  {
    id: 1047,
    name: 'Kanisha Waycott',
    country: {
      name: 'Ecuador',
      code: 'ec',
    },
    company: 'Schroer, Gene E Esq',
    status: 'new',
    verified: false,
    activity: 80,
    representative: {
      name: 'Xuxue Feng',
      image: 'xuxuefeng.png',
    },
    balance: 9920,
  },
  {
    id: 1048,
    name: 'Emerson Bowley',
    country: {
      name: 'Finland',
      code: 'fi',
    },
    company: 'Knights Inn',
    status: 'new',
    verified: false,
    activity: 63,
    representative: {
      name: 'Stephen Shaw',
      image: 'stephenshaw.png',
    },
    balance: 78069,
  },
  {
    id: 1049,
    name: 'Blair Malet',
    country: {
      name: 'Finland',
      code: 'fi',
    },
    company: 'Bollinger Mach Shp & Shipyard',
    status: 'new',
    verified: true,
    activity: 92,
    representative: {
      name: 'Asiya Javayant',
      image: 'asiyajavayant.png',
    },
    balance: 65005,
  },
];
